version: 2
updates:

  # Maintain dependencies for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - OlegRa

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - OlegRa
