name: Build and Release

on: [push]

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Dotnet Build
      run: dotnet build -c Release

    - name: Restore .NET Tools
      run: dotnet tool restore

    - name: Coverage All Tests
      run: dotnet dotcover test --dcXML=Configuration.xml

    - name: Save DateTimeOnly Packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          DateTimeOnly/bin/Release/*.nupkg
          DateTimeOnly/bin/Release/*.snupkg

    - name: Save DateTimeOnly.Json Packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-json
        path: |
          DateTimeOnly.Json/bin/Release/*.nupkg
          DateTimeOnly.Json/bin/Release/*.snupkg

  publish-main:
    name: Publish Binaries
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'OlegRa/System.DateTimeOnly' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Load Packages
      uses: actions/download-artifact@v5
      with:
        name: packages

    - name: Create NuGet Version
      run: dotnet nuget push **.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref }}
        draft: true

  publish-json:
    name: Publish Binaries
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'OlegRa/System.DateTimeOnly' && startsWith(github.ref, 'refs/tags/j')

    steps:
    - name: Load Packages
      uses: actions/download-artifact@v5
      with:
        name: packages-json

    - name: Create NuGet Version
      run: dotnet nuget push **.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref }}
        draft: true
