name: Build and Release

on: [push]

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Dotnet Build
      run: dotnet build -c Release

    - name: Save Packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          DateTimeOnly/bin/Release/*.nupkg
          DateTimeOnly/bin/Release/*.snupkg

  publish-sdk:
    name: Publish Binaries
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'OlegRa/System.DateTimeOnly' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Load Packages
      uses: actions/download-artifact@v3
      with:
        name: packages

    - name: Create NuGet Version
      run: dotnet nuget push **.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        draft: true
